import type { Metadata } from "next";
import { Nunito, Nunito_Sans } from "next/font/google";
import { createClient } from "@/prismicio";
import Header from "@/components/Header";
import clsx from "clsx";
import "./globals.css";
import Footer from "@/components/Footer";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export async function generateMetadata(): Promise<Metadata> {
  const client = createClient();
  const settings = await client.getSingle("settings");

  return {
    title: settings.data.site_title || "Flowrise fallback",
    description: settings.data.meta_description || "Flowrise is relaxing for you.",
    openGraph: {
      images: [settings.data.og_image.url || ""],
    },
  };
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(nunito.variable, nunitoSans.variable)}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
